version: '3.8'

services:
  app_transaction:
    build: .
    container_name: app_transaction
    volumes:
      - ./:/var/www
    depends_on:
      - app-redis

  app-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "9004:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app_transaction

  app-redis:
    image: redis:alpine
    expose:
      - 6379

networks:
  default:
    external:
      name: simplified-payment-network
