version: '3.8'
services:
  app:
    build: .
    container_name: app
    # entrypoint: "sh .entrypoint.sh"
    volumes:
      - ./:/var/www
    depends_on:
      - app-mysql
      - app-redis

  app-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: simplified_payment_db
      # MYSQL_product_DATABASE: app
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    ports:
    - 8080:8080

  app-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "9005:80"
    volumes:
      - ./:/var/www
      # - .docker/nginx/nginx.conf /etc/nginx/conf.d
      # - .docker/nginx/nginx.conf /etc/nginx/nginx.conf
      # - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app-redis:
    image: redis:alpine
    expose:
      - 6379

networks:
  default:
    external:
      name: simplified-payment-network
