version: '3.8'

services:
  app_notification:
    build: .
    entrypoint: ["sh", "entrypoint.sh"]
    container_name: app_notification
    volumes:
      - ./:/var/www
    depends_on:
      - app-redis

  app-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "9007:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app_notification

  app-redis:
    image: redis:alpine
    expose:
      - 6379

networks:
  default:
    external:
      name: simplified-payment-network
